---
name: isotovideo
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  schedule:
    runs-on: ubuntu-20.04
    container:
      image: "registry.opensuse.org/devel/openqa/containers/isotovideo:qemu-x86"
    steps:
      - uses: actions/checkout@v2
      - name: Verify the test schedule including wheels
        run: ./test
        env:
          WITH_COVER_OPTIONS: 1
